# ğŸ”— Links:
# Docs: https://docs.github.com/en/actions/writing-workflows

# âœï¸ Description:
# This action is used to run eslint checks
# Runs on pull requests and pushes to  the main/master branches
# Based on the event type:
#   - If it's a pull request, it will run eslint, then add the check to the PR as well as annotate the code with the errors and warnings.
#   - If it's a push to main/master, it will run the type checking and fail if there are any errors.

# ğŸš¨ GITHUB SECRETS REQUIRED: NONE

name: Lint Check (eslint, prettier, knip)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint Check (eslint, prettier, knip)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: ğŸ”‘ Setup SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸƒâ€â™‚ï¸ Run ESLint
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: ". --ext .js,.jsx,.ts,.tsx,.astro"

      - name: ğŸƒâ€â™‚ï¸ Run ESLint
        if: github.event_name != 'pull_request'
        run: pnpm lint

      - name: ğŸƒâ€â™‚ï¸ Run Prettier
        run: pnpm format:check

      - name: ğŸƒâ€â™‚ï¸ Run Knip
        run: pnpm knip
