# ğŸ”— Links:
# Docs: https://docs.github.com/en/actions/writing-workflows

# âœï¸ Description:
# This action is used to run commitlint, biome and knip checks
# Runs on pull requests and pushes to  the main/master branches
# Based on the event type:
#   - If it's a pull request, it will run commitlint, biome and knip, then add the check to the PR as well as annotate the code with the errors and warnings.
#   - If it's a push to main/master, it will run commitlint, biome and knip and fail if there are any errors.

# ğŸš¨ GITHUB SECRETS REQUIRED: NONE

name: Lint Check (commitlint, biome, knip)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint Check (commitlint, biome, knip)
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # - name: ğŸ”‘ Setup SSH
      #   uses: webfactory/ssh-agent@v0.9.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ğŸ“¦ Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ğŸƒâ€â™‚ï¸ Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm commitlint --last --verbose

      - name: ğŸƒâ€â™‚ï¸ Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: ğŸƒâ€â™‚ï¸ Run Knip
        run: pnpm knip

      - name: ğŸƒâ€â™‚ï¸ Run Biome
        if: github.event_name == 'pull_request'
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: ğŸƒâ€â™‚ï¸ Run Biome
        if: github.event_name != 'pull_request'
        run: pnpm biome ci

